runtime: python27
api_version: 1
threadsafe: yes
service: esaybq-front-ahmed

env_variables:
  BUCKET_NAME: "easybqaa"
  DEBUG: True

skip_files:
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^(.*/)?.*\.yml$
  - ^(.*/)?LICENSE$
  - ^(.*/)?README\.md$
  - ^(.*/)?.*\.pack$

handlers:
  - url: /(.*\.(gif|png|jpg|css|js|scss|svg|ico)(|\.map))$
    static_files: dist/\1
    upload: dist/.*\.(gif|png|jpg|css|js|scss|svg|ico)(|.map)
  - url: /(.*)$
    static_files: dist/index.html
    upload: dist/index.html
  - url: /(.*\.(js|css|svg|png)(|\.map))$
    static_files: dist/\1
    upload: dist/(.*)(|.map)
  - url: /.*
    static_files: dist/index.html
    upload: dist/.*
