runtime: nodejs16
service: esaybq-front-ahmed1
instance_class: F2

env_variables:
  BUCKET_NAME: "easybqaa"
  DEBUG: True

handlers:
  - url: /(.*\.[A-Za-z0-9]{1,4})$
    static_files: dist/easy-bq/\1
    upload: dist/app/(.*\.[A-Za-z0-9]{1,4})$

  - url: /(.*)$
    static_files: dist/easy-bq/index.html
    upload: dist/easy-bq/index.html

  - url: /(.*\.(js|css|svg|png)(|\.map))$
    static_files: dist/\1
    upload: dist/(.*)(|\.map)

  - url: /.*
    static_files: dist/index.html
    upload: dist/.*
