steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install', '--force']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', '-r', 'dist', 'gs://bqls-test217.appspot.com']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--appyaml=app.yaml', '--ignore-file=.gcloudignore']
  - name: 'google/cloud-sdk'
    entrypoint: 'bash'
    args: ['-c', 'ls -lR dist']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'submit', '--config=cloudbuild.yaml']
timeout: '3000s'
