apiVersion: apps/v1
kind: Deployment
metadata:
  name: easytest-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easytest
  template:
    metadata:
      labels:
        app: easytest
    spec:
      containers:
        - name: easytest-container
          image: bouhmiid/easybb789:latest
          ports:
            - containerPort: 4200
